# The URL the site will be built for
base_url = "https://enccs.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "category", feed = false, render = false },
    { name = "difficulty", feed = false, render = false },
    { name = "maturity", feed = false, render = false },
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[search]
index_format = "fuse_javascript" # or "fuse_json"

[extra]
# Put all your custom variables here
# Define badge colors for Skill, Difficulty Level, and Maturity
badge_colors = {
    category = {
        hpc = "bg-[#FFC107]",
        ai = "bg-[#2A2B31]",
        gpu_programming = "bg-[#2A2B31]",
        cpu_programming = "bg-[#FFC107]",
        molecular_dynamics = "bg-[#2A2B31]",
        quantum_computing = "bg-[#2A2B31]",
        computational_fluid_dynamics = "bg-[#FFC107]",
        plasma_physics = "bg-[#2A2B31]",
        programming_tools = "bg-[#FFC107]",
        instructor_training = "bg-[#2A2B31]",
        basics_of_hpc = "bg-[#2A2B31]",
        electronic_structure_calculations = "bg-[#FFC107]",
        high_level_language_programming = "bg-[#2A2B31]",
    },
    difficulty = { beginner = "bg-[#00d084]", intermediate = "bg-[#FFC107]", advanced = "bg-[#FFC107]" },
    maturity = { alpha = "bg-[#FFC107]", beta = "bg-[#FFC107]", stable = "bg-[#00d084]" }
}

[extra.category_names]
hpc = "HPC"
ai = "AI"
gpu_programming = "GPU Programming"
cpu_programming = "CPU Programming"
molecular_dynamics = "Molecular Dynamics"
quantum_computing = "Quantum Computing"
computational_fluid_dynamics = "Computational Fluid Dynamics"
plasma_physics = "Plasma Physics"
programming_tools = "Programming Tools"
instructor_training = "Instructor Training"
basics_of_hpc = "Basics of HPC"
electronic_structure_calculations = "Electronic Structure Calculations"
high_level_language_programming = "High Level Language Programming"

# Navigation configuration
[extra.nav]
logo_src = "https://media.enccs.se/2026/03/ENCCS-Logo-Horizontal-White.png"
logo_alt = "ENCCS - EuroCC National Competence Centre Sweden logo"

# Footer configuration
[extra.footer]
quick_links_title = "Quick links"

[[extra.footer.quick_links]]
name = "About ENCCS"
url = "https://enccs.se/about/"

[[extra.footer.quick_links]]
name = "Contact us"
url = "https://enccs.se/contact/"

[[extra.footer.quick_links]]
name = "Events"
url = "https://enccs.se/events/"

[[extra.footer.quick_links]]
name = "All services"
url = "https://enccs.se/all-services/"

[[extra.footer.quick_links]]
name = "Privacy Policy"
url = "https://enccs.se/privacy-policy/"
